# Generated by Django 5.1.5 on 2025-02-02 23:03

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faq',
            name='answer_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='answer_hi',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_bn',
        ),
        migrations.RemoveField(
            model_name='faq',
            name='question_hi',
        ),
        migrations.AddField(
            model_name='faq',
            name='translations',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
