# Generated by Django 5.1.5 on 2025-02-03 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_faq_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='faqs', to='faqs.language'),
        ),
    ]
